# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestsalon', '0006_auto_20170223_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='salons',
            name='salon_contact',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='salons',
            name='salon_site',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
