# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bestsalon', '0008_masters_works'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
                ('cat_desc', models.CharField(max_length=250)),
                ('work_logo', models.ImageField(upload_to=b'servicecat/')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_desc', models.CharField(max_length=250)),
                ('service_price', models.CharField(max_length=250)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestsalon.ServiceCategory')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestsalon.Salons')),
            ],
        ),
    ]
