# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 09:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestsalon', '0009_servicecategory_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicecategory',
            old_name='work_logo',
            new_name='cat_logo',
        ),
    ]
