# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 06:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bestsalon', '0010_auto_20170225_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=150)),
                ('avatar', models.ImageField(default=b'users/avatar.jpg', upload_to=b'users/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
