# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestsalon', '0013_valueofsalon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valueofsalon',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='valueofsalon',
            name='sumvalue',
            field=models.IntegerField(default=0),
        ),
    ]
