# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 12:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bestsalon', '0015_auto_20170303_0455'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelfMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_status', models.CharField(max_length=500)),
                ('master_author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SelfServiceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=100)),
                ('cat_desc', models.CharField(max_length=250)),
                ('cat_logo', models.ImageField(upload_to=b'servicecat/')),
            ],
        ),
        migrations.CreateModel(
            name='SelfServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('service_desc', models.CharField(max_length=250)),
                ('service_price', models.CharField(max_length=250)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestsalon.ServiceCategory')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestsalon.SelfMaster')),
            ],
        ),
        migrations.CreateModel(
            name='SelfValueOfMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicevalue', models.IntegerField(default=0)),
                ('workvalue', models.IntegerField(default=0)),
                ('sumvalue', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestsalon.SelfMaster')),
            ],
        ),
        migrations.CreateModel(
            name='SelfWorks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_desc', models.CharField(max_length=250)),
                ('work_logo', models.ImageField(upload_to=b'works/')),
                ('work_like', models.IntegerField(default=0)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestsalon.SelfMaster')),
            ],
        ),
        migrations.AddField(
            model_name='works',
            name='work_like',
            field=models.IntegerField(default=0),
        ),
    ]
