# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bestsalon', '0018_favmasters_favsalons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favmasters',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestsalon.SelfMaster'),
        ),
    ]
