# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 06:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bestsalon', '0020_works_wholikeit'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfworks',
            name='wholikeit',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
