# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestsalon', '0021_selfworks_wholikeit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(upload_to=b'salonsphotos/')),
            ],
        ),
        migrations.AddField(
            model_name='salons',
            name='salon_photos',
            field=models.ManyToManyField(to='bestsalon.Photos'),
        ),
    ]
