# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestsalon', '0022_auto_20170308_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='salons',
            name='salon_feedback',
            field=models.ManyToManyField(to='bestsalon.Feedback'),
        ),
    ]
