# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 00:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestsalon', '0026_book_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 12, 0, 58, 55, 470448)),
        ),
    ]
