# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 04:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bestsalon', '0029_auto_20170312_0331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selfservices',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='selfservices',
            name='master',
        ),
        migrations.RemoveField(
            model_name='book',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='services',
            name='salon',
        ),
        migrations.AddField(
            model_name='book',
            name='service',
            field=models.ManyToManyField(to='bestsalon.Services'),
        ),
        migrations.AddField(
            model_name='salons',
            name='salon_services',
            field=models.ManyToManyField(to='bestsalon.Services'),
        ),
        migrations.AddField(
            model_name='selfmaster',
            name='salon_book',
            field=models.ManyToManyField(to='bestsalon.Book'),
        ),
        migrations.AddField(
            model_name='selfmaster',
            name='salon_feedback',
            field=models.ManyToManyField(to='bestsalon.Feedback'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 13, 4, 26, 19, 725580)),
        ),
        migrations.AlterField(
            model_name='selfworks',
            name='work_service',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bestsalon.Services'),
        ),
        migrations.DeleteModel(
            name='SelfServices',
        ),
    ]
