# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 06:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bestsalon', '0032_auto_20170313_0618'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_desc', models.CharField(max_length=250)),
                ('service_price', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='services',
            name='service_desc',
        ),
        migrations.RemoveField(
            model_name='services',
            name='service_price',
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 14, 6, 28, 11, 309553)),
        ),
        migrations.AlterField(
            model_name='salons',
            name='salon_services',
            field=models.ManyToManyField(to='bestsalon.MyService'),
        ),
        migrations.AlterField(
            model_name='selfmaster',
            name='master_services',
            field=models.ManyToManyField(to='bestsalon.MyService'),
        ),
        migrations.AddField(
            model_name='myservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestsalon.Services'),
        ),
    ]
