# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 10:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bestsalon', '0034_auto_20170313_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 15, 10, 7, 29, 96296)),
        ),
        migrations.AddField(
            model_name='salons',
            name='salon_city',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bestsalon.City'),
        ),
        migrations.AddField(
            model_name='selfmaster',
            name='master_city',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='bestsalon.City'),
        ),
    ]
