# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 05:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestsalon', '0035_auto_20170314_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salons',
            old_name='salon_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='selfmaster',
            old_name='master_city',
            new_name='city',
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 16, 5, 20, 15, 748801)),
        ),
    ]
