# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 06:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestsalon', '0036_auto_20170315_0520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salons',
            old_name='salon_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 16, 6, 3, 33, 909328)),
        ),
    ]
