# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 04:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bestsalon', '0037_auto_20170315_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 17, 4, 21, 22, 544945)),
        ),
        migrations.AlterField(
            model_name='salons',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bestsalon.City'),
        ),
        migrations.AlterField(
            model_name='selfmaster',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bestsalon.City'),
        ),
    ]
