# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 04:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestsalon', '0041_auto_20170316_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 17, 4, 59, 4, 163121)),
        ),
    ]
