# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 04:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestsalon', '0045_auto_20170317_0423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='city',
            new_name='adress',
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 19, 4, 19, 47, 656240)),
        ),
    ]
