# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 16:35
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bestsalon', '0046_auto_20170318_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfmaster',
            name='wholoveit',
            field=models.ManyToManyField(related_name='who_love_this_master', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 19, 16, 35, 29, 826209)),
        ),
    ]
