# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 17:57
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestsalon', '0048_auto_20170318_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 19, 17, 57, 8, 503326)),
        ),
        migrations.AlterField(
            model_name='selfmaster',
            name='wholoveit',
            field=models.ManyToManyField(blank=True, related_name='who_love_this_master', to=settings.AUTH_USER_MODEL),
        ),
    ]
